InvFil/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
] 

WebAWS/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
	path('',include('InvFil.urls'),name='Index'),
    path('admin/', admin.site.urls),
]

InvFil/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Image(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to=settings.MEDIA_URL)

    def __str__(self):
        return self.title

InvFil/forms.py
#from PIL import Image
from django import forms
from .models import Image


class ImageForm(forms.ModelForm):
    """Form for the image model"""
    class Meta:
        model = Image
        fields = ('title', 'image')
class UploadFileForm(forms.Form):
	title = forms.CharField(max_length=50)
	picture = forms.ImageField()

InvFil/views.py
from django.shortcuts import render
#from django.http import HttpResponse
from .forms import UploadFileForm
# Create your views here.

def index(request):
	if request.method == 'POST':
		form = UploadFileForm(request.POST, request.FILES)
		if form.is_valid():
			filter(request.FILES['file'])
	return render(request, 'index.html')
    #return HttpResponse("Hello, world. You're at the index.")

templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="/static/style.css">
    <title>My test page</title>
  </head>
  <body>
    <form enctype="multipart/form-data" method="POST" >
    
    <div class="form-group">
        {{form.image.label_tag}}
        <div class="file-input">
            <label class=" text-muted text-center" for="id_image">                 
                choose an image or drag and drop a one here
            </label>  
            {{form.image}}
        </div>

    </div>
</form>
</br>-----</br>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
   {{ form.as_p }}
  <button type="submit">Upload</button>
</form>

{% if img_obj %}
  <h3>Succesfully uploaded : {{img_obj.title}}</h3>
  <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">
{% endif %}
  </body>
</html> 